version: '3.8'

services:
  app:
    build:
      args:
        user: thielserra
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www/
    container_name: slimtest_api
    volumes:
      - ./:/var/www
    restart: always
    networks:
      - network

  nginx:
    image: nginx:alpine
    container_name: slimtest_nginx
    restart: always
    ports:
      - 8086:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - network

networks:
  network:
    driver: bridge